[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive", "env"] }
corelib = { path = "../corelib" }
crossterm = "0.29.0"
ratatui = "0.29.0"
