[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
engine = { version = "0.1.0", path = "../engine" }
lru = "0.16.0"
protocol = { version = "0.1.0", path = "../protocol" }
serde = "1.0.219"
uuid = { version = "1.18.0", features = ["v4", "serde"] }
